sudo: true
language: node_js
node_js: node
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install chromium-browser
  - sudo apt-get -qq install g++-4.8
env:
  - CXX=g++-4.8
script: npm test